// Auto-generated from config.schema.ts — do not edit manually.
// Re-generate: scripts/generate-editor-types.ts

/** Defines an object that is generated by the integrator to uniquely identify a file in its system */
export interface EditorConfigDocumentReferenceData {
    /**
     * The unique document identifier used by the service to get a link to the file
     * @example "BCFA2CED"
     */
    fileKey?: string
    /**
     * The unique system identifier
     * @example "https://example.com"
     */
    instanceId?: string
}

/** Defines the groups whose comments the user can edit, remove and/or view */
export interface EditorConfigDocumentPermissionsCommentGroups {
    edit?: string[] | string
    remove?: string[] | string
    view?: string[] | string
}

/** Allows to change the permission for the document to be edited and downloaded or not */
export interface EditorConfigDocumentPermissions {
    /**
     * Allows to display the Restore button when using the onRequestRestore event. Default: false. Deprecated since 5.5.
     * @example true
     */
    changeHistory?: boolean
    /**
     * Defines if the chat functionality is enabled in the document. Default: true
     * @example true
     */
    chat?: boolean
    /**
     * Defines if the document can be commented or not. Default coincides with edit parameter.
     * @example true
     */
    comment?: boolean
    /**
     * Defines the groups whose comments the user can edit, remove and/or view
     */
    commentGroups?: EditorConfigDocumentPermissionsCommentGroups
    /**
     * Defines if the content can be copied to the clipboard. Default: true
     * @example true
     */
    copy?: boolean
    /**
     * Defines if the user can delete only his/her comments. Default: false
     * @example true
     */
    deleteCommentAuthorOnly?: boolean
    /**
     * Defines if the document can be downloaded or only viewed/edited online. Default: true
     * @example true
     */
    download?: boolean
    /**
     * Defines if the document can be edited or only viewed. Default: true
     * @example true
     */
    edit?: boolean
    /**
     * Defines if the user can edit only his/her comments. Default: false
     * @example true
     */
    editCommentAuthorOnly?: boolean
    /**
     * Defines if the forms can be filled. Default coincides with edit or review parameter.
     * @example true
     */
    fillForms?: boolean
    /**
     * Defines if the content control settings can be changed. Default: true
     * @example true
     */
    modifyContentControl?: boolean
    /**
     * Defines if the filter can be applied globally (true) or locally (false). Default: true
     * @example true
     */
    modifyFilter?: boolean
    /**
     * Defines if the document can be printed. Default: true
     * @example true
     */
    print?: boolean
    /**
     * Defines if the Protection tab on the toolbar is displayed. Default: true
     * @example true
     */
    protect?: boolean
    /**
     * Allows to display the Rename button. Default: false. Deprecated since 6.0.
     * @example true
     */
    rename?: boolean
    /**
     * Defines if the document can be reviewed. Default coincides with edit parameter.
     * @example true
     */
    review?: boolean
    /**
     * Defines the groups whose changes the user can accept/reject
     * @example ["Group1","Group2",""]
     */
    reviewGroups?: string[]
    /**
     * Defines the groups of users whose information is displayed in the editors
     * @example ["Group1",""]
     */
    userInfoGroups?: string[]
}

export interface EditorConfigDocumentInfoSharingSettingsItem {
    /**
     * Changes the user icon to the link icon
     * @example false
     */
    isLink?: boolean
    /**
     * The access rights for the user
     * @example "Full Access"
     */
    permissions?: 'Full Access' | 'Read Only' | 'Deny Access'
    /**
     * The name of the user the document will be shared with
     * @example "John Smith"
     */
    user?: string
}

/** Allows to change additional parameters for the document (owner, folder, uploading date, sharing settings) */
export interface EditorConfigDocumentInfo {
    /**
     * Defines the name of the document author/creator. Deprecated since 5.4, use owner instead.
     * @example "John Smith"
     */
    author?: string
    /**
     * Defines the document creation date. Deprecated since 5.4, use uploaded instead.
     * @example "2010-07-07 3:46 PM"
     */
    created?: string
    /**
     * Defines the highlighting state of the Favorite icon. If undefined/null, the icon is not displayed.
     * @example true
     */
    favorite?: boolean
    /**
     * Defines the folder where the document is stored (can be empty for root folder)
     * @example "Example Files"
     */
    folder?: string
    /**
     * Defines the name of the document owner/creator
     * @example "John Smith"
     */
    owner?: string
    /**
     * Displays the information about the settings which allow to share the document with other users
     */
    sharingSettings?: EditorConfigDocumentInfoSharingSettingsItem[]
    /**
     * Defines the document uploading date
     * @example "2010-07-07 3:46 PM"
     */
    uploaded?: string
}

/** Defines document parameters and access settings */
export interface EditorConfigDocument {
    /**
     * Defines the type of the file for the source viewed or edited document. Must be lowercase.
     * @example "docx"
     */
    fileType?: 'csv' | 'djvu' | 'doc' | 'docm' | 'docx' | 'dot' | 'dotm' | 'dotx' | 'dps' | 'dpt' | 'epub' | 'et' | 'ett' | 'fb2' | 'fodp' | 'fods' | 'fodt' | 'hml' | 'htm' | 'html' | 'hwp' | 'hwpx' | 'key' | 'md' | 'mht' | 'mhtml' | 'numbers' | 'odg' | 'odp' | 'ods' | 'odt' | 'otp' | 'ots' | 'ott' | 'oxps' | 'pages' | 'pdf' | 'pot' | 'potm' | 'potx' | 'pps' | 'ppsm' | 'ppsx' | 'ppt' | 'pptm' | 'pptx' | 'rtf' | 'stw' | 'sxc' | 'sxi' | 'sxw' | 'txt' | 'vsdm' | 'vsdx' | 'vssm' | 'vssx' | 'vstm' | 'vstx' | 'wps' | 'wpt' | 'xls' | 'xlsb' | 'xlsm' | 'xlsx' | 'xlt' | 'xltm' | 'xltx' | 'xml' | 'xps'
    /**
     * Defines if the PDF file is a PDF form or a standard PDF file. Default: true
     * @example true
     */
    isForm?: boolean
    /**
     * Defines the unique document identifier used by the service to recognize the document. Must be unique, max 128 characters. Allowed chars: 0-9, a-z, A-Z, -._=
     * @example "Khirz6zTPdfd7"
     */
    key?: string
    /**
     * Defines an object that is generated by the integrator to uniquely identify a file in its system
     */
    referenceData?: EditorConfigDocumentReferenceData
    /**
     * Defines the desired file name for the viewed or edited document. Max 128 characters.
     * @example "Example Document Title.docx"
     */
    title?: string
    /**
     * Defines the absolute URL where the source viewed or edited document is stored
     * @example "https://example.com/url-to-example-document.docx"
     */
    url?: string
    /**
     * Allows to change the permission for the document to be edited and downloaded or not
     */
    permissions?: EditorConfigDocumentPermissions
    /**
     * Allows to change additional parameters for the document (owner, folder, uploading date, sharing settings)
     */
    info?: EditorConfigDocumentInfo
}

/** Defines the co-editing mode (Fast or Strict) and the possibility to change it */
export interface EditorConfigEditorConfigCoEditing {
    /**
     * The co-editing mode. Default: fast
     * @example "fast"
     */
    mode?: 'fast' | 'strict'
    /**
     * Defines if the co-editing mode can be changed in the editor interface. Default: true
     * @example true
     */
    change?: boolean
}

export interface EditorConfigEditorConfigRecentItem {
    /**
     * The folder where the document is stored
     * @example "Example Files"
     */
    folder?: string
    /**
     * The document title that will be displayed in the Open Recent menu
     * @example "exampledocument1.docx"
     */
    title?: string
    /**
     * The absolute URL to the document
     * @example "https://example.com/exampledocument1.docx"
     */
    url?: string
}

export interface EditorConfigEditorConfigTemplatesItem {
    /**
     * The absolute URL to the image for template
     * @example "https://example.com/exampletemplate1.png"
     */
    image?: string
    /**
     * The template title that will be displayed in the Create New menu
     * @example "exampletemplate1.docx"
     */
    title?: string
    /**
     * The absolute URL to the document where it will be created
     * @example "https://example.com/url-to-create-template1"
     */
    url?: string
}

/** Defines the user currently viewing or editing the document */
export interface EditorConfigEditorConfigUser {
    /**
     * The first name of the user. Deprecated since 4.2, use user.name instead
     * @example "John"
     */
    firstname?: string
    /**
     * The group (or several groups separated with commas) the user belongs to
     * @example "Group1,Group2"
     */
    group?: string
    /**
     * The identification of the user. Max 128 characters. Recommended to use anonymized hash.
     * @example "78e1e841"
     */
    id?: string
    /**
     * The path to the user's avatar
     * @example "https://example.com/url-to-user-avatar.png"
     */
    image?: string
    /**
     * The last name of the user. Deprecated since 4.2, use user.name instead
     * @example "Smith"
     */
    lastname?: string
    /**
     * The full name of the user. Max 128 characters. Used since version 4.2.
     * @example "John Smith"
     */
    name?: string
}

/** Defines anonymous user settings */
export interface EditorConfigEditorConfigCustomizationAnonymous {
    /**
     * Defines if to request anonymous user label
     * @example true
     */
    request?: boolean
    /**
     * The label for anonymous users
     * @example "Guest"
     */
    label?: string
}

/** Defines settings for the Close button */
export interface EditorConfigEditorConfigCustomizationClose {
    visible?: boolean
    text?: string
}

/** Defines customer information */
export interface EditorConfigEditorConfigCustomizationCustomer {
    address?: string
    info?: string
    logo?: string
    logoDark?: string
    mail?: string
    name?: string
    phone?: string
    www?: string
}

/** Defines feature settings */
export interface EditorConfigEditorConfigCustomizationFeatures {
    /**
     * Defines if tooltips about new editor features will be displayed. Default: true
     * @example true
     */
    featuresTips?: boolean
    /**
     * Defines if role settings are disabled in pdf forms. Default: true
     * @example true
     */
    roles?: boolean
    /**
     * Defines if the spell checker is enabled
     * @example true
     */
    spellcheck?: boolean | { mode?: boolean }
    /**
     * Defines the background of the top toolbar tabs
     */
    tabBackground?: 'header' | 'toolbar' | { mode?: 'header' | 'toolbar'; change?: boolean }
    /**
     * Defines the style of the top toolbar tabs
     */
    tabStyle?: 'fill' | 'line' | { mode?: 'fill' | 'line'; change?: boolean }
}

/** Defines settings for the Open file location menu button */
export interface EditorConfigEditorConfigCustomizationGoback {
    /**
     * Opens the website in a new browser tab (true) or current tab (false). Default: true
     * @example true
     */
    blank?: boolean
    /**
     * Calls events.onRequestClose instead of opening a browser tab. Deprecated since 8.1.
     * @example false
     */
    requestClose?: boolean
    /**
     * The text for the Open file location button
     * @example "Open file location"
     */
    text?: string
    /**
     * The absolute URL to open when clicking the button
     * @example "https://example.com"
     */
    url?: string
}

/** Changes the image file at the top left corner of the editor header. Recommended height: 20 pixels. */
export interface EditorConfigEditorConfigCustomizationLogo {
    /**
     * Path to the image file (300x20)
     * @example "https://example.com/logo.png"
     */
    image?: string
    /**
     * Path to the image file for dark header (300x20)
     * @example "https://example.com/dark-logo.png"
     */
    imageDark?: string
    /**
     * Path to the image file for light header (300x20)
     * @example "https://example.com/light-logo.png"
     */
    imageLight?: string
    /**
     * Path to the image file for embedded mode (248x40). Deprecated since 7.0.
     * @example "https://example.com/logo_em.png"
     */
    imageEmbedded?: string
    /**
     * The absolute URL which will be used when someone clicks the logo image
     * @example "https://example.com"
     */
    url?: string
    /**
     * Shows or hides the logo. Default: true
     * @example true
     */
    visible?: boolean
}

/** Defines the mobile document editor settings */
export interface EditorConfigEditorConfigCustomizationMobile {
    /**
     * Defines whether the view mode is enabled on launch. Default: true
     * @example true
     */
    forceView?: boolean
    /**
     * Defines whether the Document Info button is displayed. Default: false
     * @example false
     */
    info?: boolean
    /**
     * Defines whether the editor will be opened in Standard view. Default: false
     * @example false
     */
    standardView?: boolean
}

/** Contains the information about the review mode */
export interface EditorConfigEditorConfigCustomizationReview {
    /**
     * Defines if the Display mode button is displayed on the Collaboration tab. Default: false
     * @example false
     */
    hideReviewDisplay?: boolean
    /**
     * Defines the review display mode: tooltips (true) or balloons (false). Default: false
     * @example false
     */
    hoverMode?: boolean
    /**
     * Defines the review display mode. Default: original
     * @example "original"
     */
    reviewDisplay?: 'markup' | 'simple' | 'final' | 'original'
    /**
     * Defines if the review changes panel is automatically displayed. Default: false
     * @example false
     */
    showReviewChanges?: boolean
    /**
     * Defines if the document is opened in the review editing mode. Default: depends on document.permissions.review
     * @example true
     */
    trackChanges?: boolean
}

export interface EditorConfigEditorConfigCustomizationLayoutHeader {
    /**
     * Defines if the header is displayed in edit mode. Default: true
     * @example true
     */
    editMode?: boolean
    /**
     * Defines if the Save button is displayed. Default: true
     * @example true
     */
    save?: boolean
    /**
     * Defines if the user name and avatar are displayed. Default: true
     * @example true
     */
    user?: boolean
    /**
     * Defines if the button with the editing users is displayed. Default: true
     * @example true
     */
    users?: boolean
}

/** Defines UI layout settings */
export interface EditorConfigEditorConfigCustomizationLayout {
    header?: EditorConfigEditorConfigCustomizationLayoutHeader
    /**
     * Defines the left menu settings
     */
    leftMenu?: boolean | { mode?: boolean; navigation?: boolean; spellcheck?: boolean }
    /**
     * Defines the right menu settings
     */
    rightMenu?: boolean | { mode?: boolean }
    /**
     * Defines the status bar settings
     */
    statusBar?: boolean | { actionStatus?: boolean; docLang?: boolean; textLang?: boolean }
    /**
     * Defines the toolbar settings
     */
    toolbar?: boolean | { collaboration?: boolean | { mailmerge?: boolean }; draw?: boolean; file?: boolean | { close?: boolean; info?: boolean; save?: boolean; settings?: boolean }; home?: Record<string, never>; layout?: boolean; plugins?: boolean; protect?: boolean; references?: boolean; save?: boolean; view?: boolean | { navigation?: boolean } }
}

/** Allows to customize editor interface and behavior */
export interface EditorConfigEditorConfigCustomization {
    /**
     * Defines if the About menu button is displayed or hidden
     * @example true
     */
    about?: boolean
    /**
     * Defines anonymous user settings
     */
    anonymous?: EditorConfigEditorConfigCustomizationAnonymous
    /**
     * Defines if autosave is enabled or disabled
     * @example true
     */
    autosave?: boolean
    /**
     * Defines settings for the Close button
     */
    close?: EditorConfigEditorConfigCustomizationClose
    /**
     * Defines if the comments functionality is enabled
     * @example true
     */
    comments?: boolean
    /**
     * Defines if the editor header is displayed in a compact mode
     * @example false
     */
    compactHeader?: boolean
    /**
     * Defines if the editor toolbar is displayed in a compact mode
     * @example false
     */
    compactToolbar?: boolean
    /**
     * Defines if compatible features are enabled
     * @example false
     */
    compatibleFeatures?: boolean
    /**
     * Defines customer information
     */
    customer?: EditorConfigEditorConfigCustomizationCustomer
    /**
     * Defines feature settings
     */
    features?: EditorConfigEditorConfigCustomizationFeatures
    /**
     * Defines settings for the Feedback & Support menu button. Default: false
     */
    feedback?: boolean | { url?: string; visible?: boolean }
    /**
     * Adds the request for force saving when saving the document. Default: false
     * @example false
     */
    forcesave?: boolean
    /**
     * Defines if Western (true) or Chinese (false) font size is used in Chinese UI. Default: false
     * @example false
     */
    forceWesternFontSize?: boolean
    /**
     * Defines settings for the Open file location menu button
     */
    goback?: EditorConfigEditorConfigCustomizationGoback
    /**
     * Defines if the Help menu button is displayed or hidden. Default: true
     * @example true
     */
    help?: boolean
    /**
     * Defines if the note panel is displayed or hidden on first loading. Available for presentation editor only. Default: false
     * @example false
     */
    hideNotes?: boolean
    /**
     * Defines if the right menu is displayed or hidden on first loading. Default: true
     * @example true
     */
    hideRightMenu?: boolean
    /**
     * Defines if the editor rulers are displayed or hidden. Default: false for documents, true for presentations
     * @example false
     */
    hideRulers?: boolean
    /**
     * Defines the mode of embedding editors into the web page
     * @example "embed"
     */
    integrationMode?: string
    /**
     * Changes the image file at the top left corner of the editor header. Recommended height: 20 pixels.
     */
    logo?: EditorConfigEditorConfigCustomizationLogo
    /**
     * Defines if document macros will be automatically run when the editor opens. Default: true
     * @example true
     */
    macros?: boolean
    /**
     * Defines the macros run mode when autostart is enabled. Default: warn
     * @example "warn"
     */
    macrosMode?: 'disable' | 'warn' | 'enable'
    /**
     * Defines the hint that describes the event after mentions in a comment. Default: true
     * @example true
     */
    mentionShare?: boolean
    /**
     * Defines the mobile document editor settings
     */
    mobile?: EditorConfigEditorConfigCustomizationMobile
    /**
     * Defines if the mobile document editor is opened in view/edit mode on launch. Deprecated since 8.2, use mobile parameter instead.
     * @example true
     */
    mobileForceView?: boolean
    /**
     * Defines if plugins will be launched and available. Default: true
     * @example true
     */
    plugins?: boolean
    /**
     * Defines the pointer mode when the presentation editor is loaded in the viewer. Default: select
     * @example "select"
     */
    pointerMode?: 'select' | 'hand'
    /**
     * Contains the information about the review mode
     */
    review?: EditorConfigEditorConfigCustomizationReview
    /**
     * Defines the review editing mode in the document editor. Deprecated since 7.0, use review.reviewDisplay instead.
     * @example "original"
     */
    reviewDisplay?: 'markup' | 'simple' | 'final' | 'original'
    /**
     * Defines if the horizontal scroll is automatically displayed when the spreadsheet editor is loaded. Available since 8.3. Default: true
     * @example true
     */
    showHorizontalScroll?: boolean
    /**
     * Defines if the review changes panel is automatically displayed. Deprecated since 7.0, use review.showReviewChanges instead.
     * @example false
     */
    showReviewChanges?: boolean
    /**
     * Defines if the vertical scroll is automatically displayed when the spreadsheet editor is loaded. Available since 8.3. Default: true
     * @example true
     */
    showVerticalScroll?: boolean
    /**
     * Defines the background color for the slide show in the presentation editor. Can be HEX, RGB, or RGBA. Available since 8.3.
     * @example "#000000"
     */
    slidePlayerBackground?: string
    /**
     * Defines if the spell checker is automatically switched on or off. Deprecated since 7.1, use features.spellcheck instead.
     * @example true
     */
    spellcheck?: boolean
    /**
     * Defines the Complete & Submit button settings. Available since 8.3. Default: true
     */
    submitForm?: boolean | { visible?: boolean; resultMessage?: string }
    /**
     * Defines whether the Suggest a Feature menu button will be displayed. Default: true
     * @example true
     */
    suggestFeature?: boolean
    /**
     * Defines if the document title is visible on the top toolbar. Default: false
     * @example false
     */
    toolbarHideFileName?: boolean
    /**
     * Defines if the top toolbar tabs are distinctly displayed (false) or only highlighted (true). Deprecated since 8.2.
     * @example false
     */
    toolbarNoTabs?: boolean
    /**
     * Defines if the document is opened in the review editing mode. Deprecated since 7.0, use review.trackChanges instead.
     * @example true
     */
    trackChanges?: boolean
    /**
     * Defines the editor theme settings. Default: theme-classic-light
     * @example "theme-dark"
     */
    uiTheme?: 'theme-light' | 'theme-classic-light' | 'theme-dark' | 'theme-contrast-dark' | 'theme-white' | 'theme-night' | 'default-dark' | 'default-light'
    /**
     * Defines the measurement units used on the ruler. Default: cm
     * @example "cm"
     */
    unit?: 'cm' | 'pt' | 'inch'
    /**
     * Defines the HEX color for the default heading styles in the document editor. Available since 8.3.
     * @example "#00ff00"
     */
    wordHeadingsColor?: string
    /**
     * Defines the document display zoom value in percent. Can be -1 (fit to page) or -2 (fit width). Default: 100
     * @example 100
     */
    zoom?: number
    /**
     * Defines UI layout settings
     */
    layout?: EditorConfigEditorConfigCustomizationLayout
    /**
     * Defines if the left menu panel is displayed or hidden. Deprecated since 7.1, use layout.leftMenu instead.
     * @example true
     */
    leftMenu?: boolean
    /**
     * Defines the path to the image logo which will be displayed while the document is being loaded
     * @example "https://example.com/loader-logo.png"
     */
    loaderLogo?: string
    /**
     * Defines the text which will be displayed while the document is being loaded
     * @example "The document is loading, please wait..."
     */
    loaderName?: string
    /**
     * Defines if the right menu panel is displayed or hidden. Deprecated since 7.1, use layout.rightMenu instead.
     * @example true
     */
    rightMenu?: boolean
    /**
     * Defines if the status bar is displayed or hidden. Deprecated since 7.1, use layout.statusBar instead.
     * @example true
     */
    statusBar?: boolean
    /**
     * Defines if the top toolbar is displayed or hidden. Deprecated since 7.1, use layout.toolbar instead.
     * @example true
     */
    toolbar?: boolean
}

/** Defines settings for the embedded viewer */
export interface EditorConfigEditorConfigEmbedded {
    /**
     * Defines the absolute URL which will be used when clicking the embed button
     * @example "https://example.com/embedded?doc=document1.docx"
     */
    embedUrl?: string
    /**
     * Defines the absolute URL which will be used when clicking the fullscreen button
     * @example "https://example.com/embedded?doc=document1.docx#fullscreen"
     */
    fullscreenUrl?: string
    /**
     * Defines the absolute URL that will allow the document to be saved onto the user's computer
     * @example "https://example.com/download?doc=exampledocument1.docx"
     */
    saveUrl?: string
    /**
     * Defines the absolute URL that will allow other users to share this document
     * @example "https://example.com/view?doc=exampledocument1.docx"
     */
    shareUrl?: string
    /**
     * Defines the place for the embedded viewer toolbar
     * @example "top"
     */
    toolbarDocked?: 'top' | 'bottom'
}

/** Defines plugin configuration */
export interface EditorConfigEditorConfigPlugins {
    /**
     * Defines the array of plugin GUIDs that will be automatically started
     * @example ["asc.{7327FC95-16DA-41D9-9AF2-0E7F449F6800}"]
     */
    autostart?: string[]
    /**
     * Defines an object which allows configuring plugins from an external source
     */
    options?: Record<string, Record<string, unknown>>
    /**
     * Defines the array of absolute URLs to the plugin configuration files (config.json)
     * @example ["https://example.com/plugins/chess-plugin/config.json"]
     */
    pluginsData?: string[]
    /**
     * Defines the absolute URL to the directory where the plugins are stored. Deprecated since 4.3.
     * @example "https://example.com/plugins/"
     */
    url?: string
}

/** Allows to change the parameters pertaining to the editor interface: opening mode, language, buttons, etc. */
export interface EditorConfigEditorConfig {
    /**
     * Specifies the data received from the document editing service using the onMakeActionLink event or the onRequestSendNotify event
     * @example "ACTION_DATA"
     */
    actionLink?: string
    /**
     * Specifies absolute URL to the document storage service (required)
     * @example "https://example.com/url-to-callback.ashx"
     */
    callbackUrl?: string
    /**
     * Defines the co-editing mode (Fast or Strict) and the possibility to change it
     */
    coEditing?: EditorConfigEditorConfigCoEditing
    /**
     * Defines the absolute URL of the document where it will be created and available after creation
     * @example "https://example.com/url-to-create-document/"
     */
    createUrl?: string
    /**
     * Defines the editor interface language using two-letter language codes (de, ru, it, etc.). For Portuguese (Portugal) or Chinese (Traditional, Taiwan) use pt-PT or zh-TW. Default: en
     * @example "en"
     */
    lang?: string
    /**
     * Defines the default measurement units. Specify us or ca for inches. Deprecated since 8.2, use region parameter instead.
     * @example ""
     */
    location?: string
    /**
     * Defines the editor opening mode. Default: edit
     * @example "edit"
     */
    mode?: 'view' | 'edit'
    /**
     * Defines the presence or absence of the documents in the Open Recent menu option
     */
    recent?: EditorConfigEditorConfigRecentItem[]
    /**
     * Defines the default display format for currency and date/time using four letter codes (en-US, fr-FR, etc.). Default: en-US
     * @example "en-US"
     */
    region?: string
    /**
     * Defines the presence or absence of the templates in the Create New menu option
     */
    templates?: EditorConfigEditorConfigTemplatesItem[]
    /**
     * Defines the user currently viewing or editing the document
     */
    user?: EditorConfigEditorConfigUser
    /**
     * Allows to customize editor interface and behavior
     */
    customization?: EditorConfigEditorConfigCustomization
    /**
     * Defines settings for the embedded viewer
     */
    embedded?: EditorConfigEditorConfigEmbedded
    /**
     * Defines plugin configuration
     */
    plugins?: EditorConfigEditorConfigPlugins
}

/** Defines event handlers for document editor */
export interface EditorConfigEvents {
    /**
     * The function called when the application is loaded into the browser
     */
    onAppReady?: string
    /**
     * The function called when the document is co-edited by another user in the strict co-editing mode
     */
    onCollaborativeChanges?: string
    /**
     * The function called when the document is loaded into the document editor
     */
    onDocumentReady?: string
    /**
     * The function called when the document is modified
     */
    onDocumentStateChange?: string
    /**
     * The function called with the absolute URL to the edited file when the downloadAs method is being called
     */
    onDownloadAs?: string
    /**
     * The function called when an error or some other specific event occurs
     */
    onError?: string
    /**
     * The function called when the application opened the file
     */
    onInfo?: string
    /**
     * The function called when the user is trying to get link for opening the document which contains a bookmark
     */
    onMakeActionLink?: string
    /**
     * The function called when the meta information of the document is changed via the meta command
     */
    onMetaChange?: string
    /**
     * The function called after the error is shown, when the document is opened for editing with the old document.key value. Deprecated since 8.3, use onRequestRefreshFile instead.
     */
    onOutdatedVersion?: string
    /**
     * The function called when all plugins are loaded and can be used
     */
    onPluginsReady?: string
    /**
     * The function called when the application is loaded into the browser. Deprecated since 5.0, use onAppReady instead.
     */
    onReady?: string
    /**
     * The function called when the user is trying to end the work with the editor and close it
     */
    onRequestClose?: string
    /**
     * The function called when the user is trying to select document for comparing. Available only for ONLYOFFICE Docs Enterprise. Deprecated since 7.5, use onRequestSelectDocument instead.
     */
    onRequestCompareFile?: string
    /**
     * The function called when the user is trying to create document by clicking the Create New button
     */
    onRequestCreateNew?: string
    /**
     * The function called when the user is trying to switch the document from viewing into editing mode
     */
    onRequestEditRights?: string
    /**
     * The function called when the user is trying to show the document version history
     */
    onRequestHistory?: string
    /**
     * The function called when the user is trying to go back to the document from viewing the document version history
     */
    onRequestHistoryClose?: string
    /**
     * The function called when the user is trying to click the specific document version in the document version history
     */
    onRequestHistoryData?: string
    /**
     * The function called when the user is trying to insert an image by clicking the Image from Storage button
     */
    onRequestInsertImage?: string
    /**
     * The function called when the user is trying to select recipients data by clicking the Mail merge button. Deprecated since 7.5, use onRequestSelectSpreadsheet instead.
     */
    onRequestMailMergeRecipients?: string
    /**
     * The function called when the user is trying to open an external link by clicking the Open source button
     */
    onRequestOpen?: string
    /**
     * The function called when the user is trying to refresh data inserted from the external file
     */
    onRequestReferenceData?: string
    /**
     * The function called when the user is trying to change a source of the external data by clicking the Change source button
     */
    onRequestReferenceSource?: string
    /**
     * The function called instead of the onOutdatedVersion event when the editor is opened with key that was already used or when reconnecting after losing connection
     */
    onRequestRefreshFile?: string
    /**
     * The function called when the user is trying to rename the file by clicking the Rename button
     */
    onRequestRename?: string
    /**
     * The function called when the user is trying to restore the file version by clicking the Restore button in the version history
     */
    onRequestRestore?: string
    /**
     * The function called when the user is trying to save file by clicking Save Copy as button
     */
    onRequestSaveAs?: string
    /**
     * The function called when the user is trying to select a document for comparing, combining, or inserting text
     */
    onRequestSelectDocument?: string
    /**
     * The function called when the user is trying to select recipients data by clicking the Mail merge button
     */
    onRequestSelectSpreadsheet?: string
    /**
     * The function called when the user is mentioned in a comment
     */
    onRequestSendNotify?: string
    /**
     * The function called when the user is trying to manage document access rights
     */
    onRequestSharingSettings?: string
    /**
     * The function called when the user is trying to start filling out the ready forms in pdf editing mode
     */
    onRequestStartFilling?: string
    /**
     * The function called when the user can select other users to mention in the comments or grant the access rights
     */
    onRequestUsers?: string
    /**
     * The function called when the force saving request is successfully performed, when the Complete & Submit button is clicked
     */
    onSubmit?: string
    /**
     * The function called when a user action is required to open a document (password, encoding selection, etc.)
     */
    onUserActionRequired?: string
    /**
     * The function called when a warning occurs
     */
    onWarning?: string
}

export interface EditorConfig {
    /**
     * Defines the document type to be opened
     * @example "cell"
     */
    documentType?: 'word' | 'cell' | 'slide' | 'pdf' | 'diagram'
    /**
     * Defines the document height (100% by default) in the browser window
     * @example "100%"
     * @example "550px"
     */
    height?: string
    /**
     * Defines the document width (100% by default) in the browser window
     * @example "100%"
     */
    width?: string
    /**
     * Defines the encrypted signature added to the ONLYOFFICE Docs config in the form of a token
     * @example "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.LwimMJA3puF3ioGeS-tfczR3370GXBZMIL-bdpu4hOU"
     */
    token?: string
    /**
     * Defines the platform type used to access the document. Default: desktop
     * @example "desktop"
     */
    type?: 'desktop' | 'mobile' | 'embedded'
    /**
     * Defines document parameters and access settings
     */
    document?: EditorConfigDocument
    /**
     * Allows to change the parameters pertaining to the editor interface: opening mode, language, buttons, etc.
     */
    editorConfig?: EditorConfigEditorConfig
    /**
     * Defines event handlers for document editor
     */
    events?: EditorConfigEvents
}
